pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform"
    }
    parameters {
        string(name: 'LAMBDA_URL', defaultValue: '', description: 'URL to the Lamdba function')
        string(name: 'WORKSPACE', defaultValue: 'development', description:'worspace to use in Terraform')
        string(name: 'DYNAMODB_STATELOCK', defaultValue: 'ddt-tfstatelock', description:'DynamoDB table for state locking')
        string(name: 'NETWORKING_BUCKET', defaultValue: '', description:'S3 bucket to use data source')
        string(name: 'APPLICATION_BUCKET', defaultValue: '', description:'S3 bucket to use for state locking')
        string(name: 'REGION', defaultValue: 'us-east-1', description:'Region for resources')
        string(name: 'DATASOURCE', defaultValue: '', description:'Table name for datasource')
        string(name: 'KEYNAME', defaultValue: 'PluralsightKeys', description:'Keys for EC2 instances')

    }
    environment {
        TF_HOME = tool('terraform')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        APPLICATION_ACCESS_KEY = credentials('application_access_key')
        APPLICATION_SECRET_KEY = credentials('application_secret_key')
    }
    stages {
        stage('ApplicationInit'){
            steps {
                dir('module5/5-applications/'){
                    sh "terraform init -input=false -plugin-dir=/var/jenkins_home/terraform_plugins \
                     --backend-config='dynamodb_table=${params.DYNAMODB_STATELOCK}' --backend-config='bucket=${params.APPLICATION_BUCKET}' \
                     --backend-config='access_key=$APPLICATION_ACCESS_KEY' --backend-config='secret_key=$APPLICATION_SECRET_KEY' \
                     --backend-config='region=${params.REGION}'"
                    sh "echo \$PWD"
                    sh "whoami"
                }
            }
        }
        stage('ApplicationPlan'){
            steps {
                dir('module5/5-applications/'){
                    script {
                        try {
                            sh "terraform workspace new ${params.WORKSPACE}"
                        } catch (err) {
                            sh "terraform workspace select ${params.WORKSPACE}"
                        }
                        sh "terraform plan -var 'aws_access_key=$APPLICATION_ACCESS_KEY' \
                        -var 'aws_secret_key=$APPLICATION_SECRET_KEY' \
                        -var 'url=${params.LAMBDA_URL}' -var 'region=${params.REGION}' \
                        -var 'tablename=${params.DATASOURCE}' -var 'key_name=${params.KEYNAME}' \
                        -var 'network_remote_state_bucket=${params.NETWORKING_BUCKET}' \
                        -input=false -out terraform-application.tfplan;echo \$? > status"
                        stash name: "terraform-application-plan", includes: "terraform-application.tfplan"
                    }
                }
            }
        }
        stage('ApplicationApply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        dir('module5/5-applications'){
                            sh "terraform destroy -var 'aws_access_key=$APPLICATION_ACCESS_KEY' \
                             -var 'aws_secret_key=$APPLICATION_SECRET_KEY' -var 'url=${params.LAMBDA_URL}' \
                             -var 'region=${params.REGION}' -var 'tablename=${params.DATASOURCE}' \
                             -var 'key_name=${params.KEYNAME}' \
                             -var 'network_remote_state_bucket=${params.NETWORKING_BUCKET}' -auto-approve"
                        }
                         currentBuild.result = 'UNSTABLE'
                    }
                    if(apply){
                        dir('module5/5-applications'){
                            unstash "terraform-application-plan"
                            sh 'terraform apply terraform-application.tfplan'
                        }
                    }
                }
            }
        }
    }
}