pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY = credentials('aws_access_key')
        AWS_SECRET_KEY = credentials('aws_secret_key')
    }
    tools {
        org.jenkinsci.plugins.terraform.TerraformInstallation
    }
    stages {
        stage('Init'){
            steps {
                dir('module5/'){
                    sh 'terraform --version'
                    sh "terraform init -input=false"
                    sh "echo \$PWD"
                    sh "whoami"
                }
            }
        }
        stage('Plan'){
            steps {
                dir('module5/'){
                    sh "terraform plan -var 'aws_access_key=$AWS_ACCESS_KEY' -var 'aws_secret_key=$AWS_SECRET_KEY' -out=terraform.tfplan;echo \$? > status"
                    stash name: "terraform-plan", includes: "terraform.tfplan"
                }
            }
        }
        stage('Apply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        sh "terraform destroy -force"
                        currentBuild.result = 'UNSTABLE'
                    }
                    if(apply){
                        dir('module5'){
                            unstash "terraform-plan"
                            sh 'terraform apply terraform.tfplan'
                        }
                    }
                }
            }
        }
    }

}